/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package scanette;

import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;
import javax.swing.table.DefaultTableModel;
import scanette.classesMetier.Article;
import scanette.classesMetier.Magasin;
import scanette.classesMetier.Scannette;

/**
 *
 * @author Moi
 */
public class JFScannette extends javax.swing.JFrame {

    /**
     * Creates new form JFScannette
     */
    public JFScannette() {
        initComponents();
    }

    public JFScannette(Magasin magasin, Scannette scannette) {
        initComponents();
        
        
        this.leMagasin = magasin;
        this.laScannette = scannette;
        
        if (scannette != null && scannette.getLeClient() !=null)
        {
            jLBienvenue.setText("Bienvenue " +scannette.getLeClient().getNom() + " dans votre magasin " + magasin.getNom() );
        }
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLBienvenue = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFNo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePanier = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTFMt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFNb = new javax.swing.JTextField();
        jBtSupprimer = new javax.swing.JButton();
        jBtTerminer = new javax.swing.JButton();
        jBtAjouter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLBienvenue.setText("Welcome ! faites vos courses MarketPlus ");
        getContentPane().add(jLBienvenue, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 18, -1, -1));

        jLabel2.setText("No de l'article à ajouter :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
        getContentPane().add(jTFNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 100, -1));

        jTablePanier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numéro", "Designation", "Prix"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTablePanier);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 380, 110));

        jLabel3.setText("Montant à payer :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jTFMt.setEditable(false);
        getContentPane().add(jTFMt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 80, -1));

        jLabel4.setText("Nb articles : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, -1, -1));

        jTFNb.setEditable(false);
        getContentPane().add(jTFNb, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 90, -1));

        jBtSupprimer.setText("Supprimer");
        jBtSupprimer.setEnabled(false);
        jBtSupprimer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtSupprimerMouseClicked(evt);
            }
        });
        getContentPane().add(jBtSupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jBtTerminer.setText("Achats Terminés");
        getContentPane().add(jBtTerminer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        jBtAjouter.setText("Ajouter");
        jBtAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtAjouterMouseClicked(evt);
            }
        });
        getContentPane().add(jBtAjouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/scanette/img/fondClair.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 52, -1, -1));

        setBounds(0, 0, 480, 401);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtAjouterMouseClicked
        // TODO add your handling code here:
        
        String strNumeroArticle = jTFNo.getText();
        
        int numeroArticle = Integer.parseInt(strNumeroArticle);
        Article article = leMagasin.RechercherArticle(numeroArticle);
        if (article == null)
        {
            JOptionPane.showMessageDialog(null, "Article non référencé");
        }
        else
        {
            laScannette.AddPanier(article);
            updateMontantPanier();
            updateNbArticle();
            
            int nbArticles = laScannette.getNbArticles();
            ((DefaultTableModel)jTablePanier.getModel()).setRowCount(nbArticles);
            
            jTablePanier.getModel().setValueAt(article.getNumero(), nbArticles-1, 0);
            jTablePanier.getModel().setValueAt(article.getDesignation(), nbArticles-1, 1);
            jTablePanier.getModel().setValueAt(article.getPrixVente(), nbArticles-1, 2);
            
            jBtSupprimer.setEnabled(true);
        }
    }//GEN-LAST:event_jBtAjouterMouseClicked

    private void jBtSupprimerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtSupprimerMouseClicked
        int noLigne = jTablePanier.getSelectedRow();
        if (noLigne <0)
        {
            JOptionPane.showMessageDialog(null, "Selectionner l'article à supprimer");
        }
        else
        {
           int numeroArticle = (int) jTablePanier.getValueAt(noLigne, 0);
           if (JOptionPane.showConfirmDialog(null, "Voulez-vous vraiment supprimer l'aticle " + numeroArticle, "Scannette", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION)
           {
               laScannette.RemovePanier(numeroArticle);
               ((DefaultTableModel)jTablePanier.getModel()).removeRow(noLigne);
               
               updateMontantPanier();
               updateNbArticle();
           }
        }
            
    }//GEN-LAST:event_jBtSupprimerMouseClicked

    private void updateMontantPanier()
    {
        String mt = String.format("%,.2f",laScannette.calculerMontantTotal());
        jTFMt.setText(mt);
    }
    
    private void updateNbArticle()
    {
        jTFNb.setText(String.valueOf(laScannette.getNbArticles()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFScannette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFScannette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFScannette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFScannette.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFScannette().setVisible(true);
            }
        });
    }
    
    private Magasin leMagasin;
    private Scannette laScannette;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAjouter;
    private javax.swing.JButton jBtSupprimer;
    private javax.swing.JButton jBtTerminer;
    private javax.swing.JLabel jLBienvenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFMt;
    private javax.swing.JTextField jTFNb;
    private javax.swing.JTextField jTFNo;
    private javax.swing.JTable jTablePanier;
    // End of variables declaration//GEN-END:variables
}
